import { BlendFunction, KernelSize } from "postprocessing";

export const BLEND_FUNC_OPTIONS = {
  ADD: BlendFunction.ADD,
  ALPHA: BlendFunction.ALPHA,
  AVERAGE: BlendFunction.AVERAGE,
  COLOR: BlendFunction.COLOR,
  COLOR_BURN: BlendFunction.COLOR_BURN,
  COLOR_DODGE: BlendFunction.COLOR_DODGE,
  DARKEN: BlendFunction.DARKEN,
  DIFFERENCE: BlendFunction.DIFFERENCE,
  DIVIDE: BlendFunction.DIVIDE,
  DST: BlendFunction.DST,
  EXCLUSION: BlendFunction.EXCLUSION,
  HARD_LIGHT: BlendFunction.HARD_LIGHT,
  HARD_MIX: BlendFunction.HARD_MIX,
  HUE: BlendFunction.HUE,
  INVERT: BlendFunction.INVERT,
  INVERT_RGB: BlendFunction.INVERT_RGB,
  LIGHTEN: BlendFunction.LIGHTEN,
  LINEAR_BURN: BlendFunction.LINEAR_BURN,
  LINEAR_DODGE: BlendFunction.LINEAR_DODGE,
  LINEAR_LIGHT: BlendFunction.LINEAR_LIGHT,
  LUMINOSITY: BlendFunction.LUMINOSITY,
  MULTIPLY: BlendFunction.MULTIPLY,
  NEGATION: BlendFunction.NEGATION,
  NORMAL: BlendFunction.NORMAL,
  OVERLAY: BlendFunction.OVERLAY,
  PIN_LIGHT: BlendFunction.PIN_LIGHT,
  REFLECT: BlendFunction.REFLECT,
  SATURATION: BlendFunction.SATURATION,
  SCREEN: BlendFunction.SCREEN,
  SET: BlendFunction.SET,
  SKIP: BlendFunction.SKIP,
  SOFT_LIGHT: BlendFunction.SOFT_LIGHT,
  SRC: BlendFunction.SRC,
  SUBTRACT: BlendFunction.SUBTRACT,
  VIVID_LIGHT: BlendFunction.VIVID_LIGHT,
};

export const KERNEL_SIZE_OPTIONS = {
  verySmall: KernelSize.VERY_SMALL,
  small: KernelSize.SMALL,
  medium: KernelSize.MEDIUM,
  large: KernelSize.LARGE,
  veryLarge: KernelSize.VERY_LARGE,
  huge: KernelSize.HUGE,
};
